"""
UttarakhandMockExams — Seed Data
8 subjects × 30 daily sets × 30 questions
"""

SUBJECTS = [
    {"name":"Mathematics",     "name_hindi":"गणित",           "icon":"📐","color_class":"m",  "exam_types":["SSC","RRB","BANK","UKSSC","UKPSC"],"sort_order":1},
    {"name":"English",         "name_hindi":"अंग्रेज़ी",       "icon":"📝","color_class":"e",  "exam_types":["SSC","RRB","BANK"],               "sort_order":2},
    {"name":"Reasoning",       "name_hindi":"तार्किक क्षमता", "icon":"🧩","color_class":"r",  "exam_types":["SSC","RRB","BANK","UKSSC"],        "sort_order":3},
    {"name":"Geography",       "name_hindi":"भूगोल",          "icon":"🌏","color_class":"g",  "exam_types":["SSC","UKSSC","UKPSC"],             "sort_order":4},
    {"name":"Hindi",           "name_hindi":"हिंदी",           "icon":"📖","color_class":"h",  "exam_types":["SSC","UKSSC","UKPSC"],             "sort_order":5},
    {"name":"History",         "name_hindi":"इतिहास",         "icon":"🏛","color_class":"hi", "exam_types":["SSC","UKSSC","UKPSC"],             "sort_order":6},
    {"name":"General Science", "name_hindi":"सामान्य विज्ञान","icon":"🔬","color_class":"sc", "exam_types":["SSC","RRB","UKSSC"],              "sort_order":7},
    {"name":"General Studies", "name_hindi":"सामान्य अध्ययन", "icon":"📚","color_class":"gs", "exam_types":["SSC","UKSSC","UKPSC"],             "sort_order":8},
]

# 30 questions per subject
QUESTIONS = {
"Mathematics": [
  {"qe":"If a train travels 360 km in 4 hours, find speed in m/s?","qh":"यदि ट्रेन 4 घंटे में 360 किमी जाए, गति m/s में?","opts":["25 m/s","90 m/s","100 m/s","40 m/s"],"ans":0,"exp":"360/4=90km/h × 1000/3600=25m/s","diff":"easy"},
  {"qe":"What is √144 + √225?","qh":"√144 + √225 का मान?","opts":["25","27","30","29"],"ans":1,"exp":"12+15=27","diff":"easy"},
  {"qe":"Shopkeeper sells at ₹520 with 30% profit. Find cost price?","qh":"30% लाभ पर ₹520 में बेचा। लागत?","opts":["₹380","₹400","₹420","₹350"],"ans":1,"exp":"CP=520×100/130=₹400","diff":"medium"},
  {"qe":"LCM of 12, 18 and 24?","qh":"12, 18 और 24 का LCM?","opts":["36","48","72","96"],"ans":2,"exp":"LCM(12,18,24)=72","diff":"easy"},
  {"qe":"If 3x + 7 = 22, then x = ?","qh":"3x + 7 = 22 में x?","opts":["3","4","5","6"],"ans":2,"exp":"3x=15, x=5","diff":"easy"},
  {"qe":"Simple interest on ₹5000 at 8% p.a. for 3 years?","qh":"₹5000 पर 8% से 3 वर्ष का SI?","opts":["₹1100","₹1200","₹1300","₹1000"],"ans":1,"exp":"SI=5000×8×3/100=₹1200","diff":"easy"},
  {"qe":"If 20% of x = 80, then x = ?","qh":"x का 20% = 80, तो x?","opts":["300","350","400","450"],"ans":2,"exp":"x=80×100/20=400","diff":"easy"},
  {"qe":"Average of 5 numbers is 40. Remove one, avg becomes 35. Find removed number?","qh":"5 संख्याओं का औसत 40, एक हटाने पर 35। हटाई संख्या?","opts":["55","60","65","70"],"ans":1,"exp":"Sum=200, New=140, Removed=60","diff":"medium"},
  {"qe":"Area of circle with radius 7 cm? (π=22/7)","qh":"7 सेमी त्रिज्या वाले वृत्त का क्षेत्रफल? (π=22/7)","opts":["144 cm²","154 cm²","132 cm²","164 cm²"],"ans":1,"exp":"22/7×49=154","diff":"easy"},
  {"qe":"Ratio 3:5, sum=96. Find larger number?","qh":"अनुपात 3:5, योग=96। बड़ी संख्या?","opts":["54","60","66","72"],"ans":1,"exp":"96×5/8=60","diff":"medium"},
  {"qe":"Profit % if CP=₹200, SP=₹250?","qh":"CP=₹200, SP=₹250 तो लाभ%?","opts":["20%","25%","30%","15%"],"ans":1,"exp":"50/200×100=25%","diff":"easy"},
  {"qe":"HCF of 36 and 48?","qh":"36 और 48 का HCF?","opts":["6","12","18","24"],"ans":1,"exp":"HCF=12","diff":"easy"},
  {"qe":"(a+b)² - (a-b)² = ?","qh":"(a+b)² - (a-b)² = ?","opts":["4ab","2ab","a²+b²","2a²"],"ans":0,"exp":"Expand: 4ab","diff":"medium"},
  {"qe":"Speed of boat in still water=15km/h, current=5km/h. Upstream speed?","qh":"शांत जल=15, धारा=5। उर्ध्वप्रवाह गति?","opts":["10 km/h","20 km/h","8 km/h","12 km/h"],"ans":0,"exp":"15-5=10km/h","diff":"easy"},
  {"qe":"A can do work in 10 days, B in 15 days. Together in?","qh":"A=10 दिन, B=15 दिन। मिलकर?","opts":["5 days","6 days","8 days","4 days"],"ans":1,"exp":"1/10+1/15=1/6 → 6 days","diff":"medium"},
  {"qe":"Compound interest on ₹1000 at 10% for 2 years?","qh":"₹1000 पर 10% से 2 वर्ष का CI?","opts":["₹200","₹210","₹205","₹220"],"ans":1,"exp":"1000×1.21-1000=₹210","diff":"medium"},
  {"qe":"What % of 150 is 45?","qh":"150 का कितना % = 45?","opts":["25%","30%","35%","20%"],"ans":1,"exp":"45/150×100=30%","diff":"easy"},
  {"qe":"Volume of cube with side 4 cm?","qh":"4 सेमी भुजा के घन का आयतन?","opts":["16 cm³","32 cm³","64 cm³","48 cm³"],"ans":2,"exp":"4³=64","diff":"easy"},
  {"qe":"Perimeter of rectangle: l=12, b=8?","qh":"आयत की परिधि: l=12, b=8?","opts":["40","36","44","48"],"ans":0,"exp":"2(12+8)=40","diff":"easy"},
  {"qe":"If x+y=10, xy=21, find x²+y²?","qh":"x+y=10, xy=21, तो x²+y²?","opts":["58","100","121","79"],"ans":0,"exp":"(10)²-2×21=58","diff":"hard"},
  {"qe":"Sum of first 20 natural numbers?","qh":"पहले 20 प्राकृतिक संख्याओं का योग?","opts":["190","200","210","180"],"ans":2,"exp":"n(n+1)/2=20×21/2=210","diff":"easy"},
  {"qe":"√(0.0016) = ?","qh":"√(0.0016) = ?","opts":["0.4","0.04","0.004","4"],"ans":1,"exp":"√(16/10000)=4/100=0.04","diff":"medium"},
  {"qe":"SP=₹90, loss=10%. Find CP?","qh":"SP=₹90, हानि=10%। CP?","opts":["₹95","₹100","₹99","₹81"],"ans":1,"exp":"CP=90×100/90=₹100","diff":"medium"},
  {"qe":"Pipe A fills in 10h, B empties in 15h. Both open, fills in?","qh":"A=10h भरता, B=15h खाली। दोनों खुले?","opts":["30 h","25 h","20 h","18 h"],"ans":0,"exp":"1/10-1/15=1/30 → 30h","diff":"hard"},
  {"qe":"Train 200m long at 72km/h crosses a pole in?","qh":"200m ट्रेन 72km/h से खंभा पार करे?","opts":["8 s","10 s","12 s","15 s"],"ans":1,"exp":"72km/h=20m/s, 200/20=10s","diff":"medium"},
  {"qe":"Discount 20% on ₹500. Selling price?","qh":"₹500 पर 20% छूट। विक्रय मूल्य?","opts":["₹380","₹400","₹420","₹350"],"ans":1,"exp":"500-100=₹400","diff":"easy"},
  {"qe":"Ages ratio 3:5. After 4 years ratio 2:3. Present ages?","qh":"उम्र अनुपात 3:5, 4 साल बाद 2:3। वर्तमान उम्र?","opts":["12 & 20","15 & 25","9 & 15","6 & 10"],"ans":0,"exp":"3x+4/5x+4=2/3 → x=4, ages=12,20","diff":"hard"},
  {"qe":"A number when divided by 5 gives remainder 3, divided by 7 gives remainder 2. Number?","qh":"5 से भाग पर शेष 3, 7 से भाग पर शेष 2। संख्या?","opts":["23","38","58","93"],"ans":0,"exp":"23÷5=4r3, 23÷7=3r2 ✓","diff":"hard"},
  {"qe":"Perimeter of equilateral triangle = 36 cm. Its area?","qh":"समबाहु त्रिभुज का परिमाप=36 सेमी। क्षेत्रफल?","opts":["36√3 cm²","72√3 cm²","18√3 cm²","54√3 cm²"],"ans":0,"exp":"Side=12, Area=√3/4×144=36√3","diff":"hard"},
  {"qe":"A mixture of 60L has milk:water = 2:1. Add 20L water. New ratio?","qh":"60L मिश्रण में दूध:पानी=2:1। 20L पानी मिलाएं। नया अनुपात?","opts":["1:1","2:3","4:3","3:2"],"ans":0,"exp":"Milk=40,Water=20+20=40 → 1:1","diff":"hard"},
],

"English": [
  {"qe":"Passive voice: 'She writes a letter.'","qh":None,"opts":["A letter was written.","A letter is written by her.","Letter is writing.","A letter written."],"ans":1,"exp":"Present simple passive = is/am/are + V3","diff":"medium"},
  {"qe":"Synonym of 'Eloquent':","qh":None,"opts":["Silent","Fluent","Rude","Dull"],"ans":1,"exp":"Eloquent = fluent and persuasive","diff":"medium"},
  {"qe":"Article before 'honest':","qh":None,"opts":["A","An","The","No article"],"ans":1,"exp":"Silent H, vowel sound /ɒ/ → 'an'","diff":"easy"},
  {"qe":"Antonym of 'Benevolent':","qh":None,"opts":["Kind","Generous","Malevolent","Charitable"],"ans":2,"exp":"Malevolent = wishing harm to others","diff":"medium"},
  {"qe":"Find error: 'He go to school every day.'","qh":None,"opts":["He","go","to school","every day"],"ans":1,"exp":"3rd person singular → 'goes'","diff":"easy"},
  {"qe":"One word: A person who cannot be corrected?","qh":None,"opts":["Invincible","Incorrigible","Indefatigable","Insolvent"],"ans":1,"exp":"Incorrigible = not able to be corrected","diff":"medium"},
  {"qe":"Fill in blank: She was tired ___ waiting.","qh":None,"opts":["by","of","from","with"],"ans":1,"exp":"Tired + of = fixed collocation","diff":"easy"},
  {"qe":"'Bite the bullet' means:","qh":None,"opts":["Shoot someone","Endure pain bravely","Eat fast","Argue angrily"],"ans":1,"exp":"To endure a painful situation stoically","diff":"medium"},
  {"qe":"Correct spelling:","qh":None,"opts":["Accomodation","Accommodation","Acommodation","Acomodation"],"ans":1,"exp":"Double 'c' and double 'm': Accommodation","diff":"easy"},
  {"qe":"Passive: 'The teacher punished the student.'","qh":None,"opts":["The student was punished by the teacher.","Student punished.","Teacher punished.","Student is punished."],"ans":0,"exp":"Past simple passive = was/were + V3","diff":"medium"},
  {"qe":"Tense: She ___ (study) for 3 hours. (Present Perfect Continuous)","qh":None,"opts":["studied","has been studying","is studying","was studying"],"ans":1,"exp":"Present Perfect Continuous for ongoing action","diff":"medium"},
  {"qe":"Phrasal verb 'Give up' means:","qh":None,"opts":["Start again","Surrender/quit","Continue","Improve"],"ans":1,"exp":"Give up = quit or surrender","diff":"easy"},
  {"qe":"Reported speech: He said, 'I am busy.'","qh":None,"opts":["He said he was busy.","He said he is busy.","He told he was busy.","He said he had been busy."],"ans":0,"exp":"Direct → Indirect: am → was","diff":"medium"},
  {"qe":"Conditional: If I ___ you, I would help.","qh":None,"opts":["am","was","were","had been"],"ans":2,"exp":"Second conditional uses 'were' for all persons","diff":"hard"},
  {"qe":"Synonym of 'Arduous':","qh":None,"opts":["Easy","Strenuous","Simple","Calm"],"ans":1,"exp":"Arduous = strenuous/extremely difficult","diff":"medium"},
  {"qe":"Choose correct sentence:","qh":None,"opts":["She do not know.","She does not knows.","She does not know.","She did not knows."],"ans":2,"exp":"Does + not + base verb (no 's' after not)","diff":"easy"},
  {"qe":"Collective noun for 'fish':","qh":None,"opts":["Pack","School","Flock","Herd"],"ans":1,"exp":"A school of fish","diff":"easy"},
  {"qe":"Preposition: She arrived ___ Monday morning.","qh":None,"opts":["in","on","at","by"],"ans":1,"exp":"on + specific day or date","diff":"easy"},
  {"qe":"Gender of 'Drake':","qh":None,"opts":["Feminine","Masculine","Neuter","Common"],"ans":1,"exp":"Drake is a male duck","diff":"medium"},
  {"qe":"Meaning of 'Plethora':","qh":None,"opts":["Scarcity","Excess/abundance","Average","Unknown"],"ans":1,"exp":"Plethora = a large or excessive amount","diff":"medium"},
  {"qe":"Active: 'The letter was written by him.' → Active?","qh":None,"opts":["He writes the letter.","He wrote the letter.","He had written the letter.","He is writing the letter."],"ans":1,"exp":"Past passive → past simple active","diff":"medium"},
  {"qe":"'In the nick of time' means:","qh":None,"opts":["Too late","At the last moment","Very fast","Too early"],"ans":1,"exp":"At the very last possible moment","diff":"easy"},
  {"qe":"Which is a conjunction?","qh":None,"opts":["Slowly","Beautiful","Although","Run"],"ans":2,"exp":"Although is a subordinating conjunction","diff":"easy"},
  {"qe":"Plural of 'Syllabus':","qh":None,"opts":["Syllabuses","Syllabi","Syllabis","Both A and B"],"ans":3,"exp":"Both 'Syllabuses' and 'Syllabi' are accepted","diff":"medium"},
  {"qe":"Gerund in: 'Swimming is good exercise.'","qh":None,"opts":["Swimming","good","exercise","is"],"ans":0,"exp":"Swimming (verb+ing used as noun) is a gerund","diff":"medium"},
  {"qe":"Fill: Neither he nor they ___ correct.","qh":None,"opts":["is","are","was","were"],"ans":1,"exp":"Verb agrees with the nearest subject 'they'","diff":"hard"},
  {"qe":"Suffix to make noun from 'Employ':","qh":None,"opts":["-ment","-ness","-ful","-less"],"ans":0,"exp":"Employment = noun form of employ","diff":"easy"},
  {"qe":"Which uses 'fewer' correctly?","qh":None,"opts":["Fewer water in glass.","Fewer students attended.","Fewer furniture here.","Fewer information given."],"ans":1,"exp":"Fewer = countable nouns; less = uncountable","diff":"medium"},
  {"qe":"Voice: 'They are building a new road.'","qh":None,"opts":["A new road is being built by them.","A new road was being built.","A new road has been built.","A new road is built by them."],"ans":0,"exp":"Present continuous passive = is/are being + V3","diff":"hard"},
  {"qe":"Idiom: 'A blessing in disguise' means:","qh":None,"opts":["A hidden curse","Something good that seemed bad","A double blessing","Disguised person"],"ans":1,"exp":"Something that seems bad but turns out to be good","diff":"medium"},
],

"Reasoning": [
  {"qe":"If APPLE is coded as ELPPA, how is MANGO coded?","qh":"APPLE = ELPPA, तो MANGO = ?","opts":["OGNAM","OGNMA","ONGAM","OGMAN"],"ans":0,"exp":"Word is written in reverse: MANGO → OGNAM","diff":"easy"},
  {"qe":"Find the odd one: 2, 5, 10, 17, 26, 36","qh":"विषम संख्या: 2, 5, 10, 17, 26, 36","opts":["17","26","36","10"],"ans":2,"exp":"Pattern +3+5+7+9+11: after 26 should be 37 not 36","diff":"medium"},
  {"qe":"A is B's sister. C is B's mother. D is C's father. How is A related to D?","qh":"A, B की बहन; C, B की माँ; D, C का पिता। A का D से क्या संबंध?","opts":["Granddaughter","Daughter","Grandmother","Niece"],"ans":0,"exp":"A→B→C→D: A is C's daughter, C is D's daughter → A is D's granddaughter","diff":"hard"},
  {"qe":"Complete the series: AZ, BY, CX, DW, ?","qh":"श्रृंखला: AZ, BY, CX, DW, ?","opts":["EV","EU","FV","EW"],"ans":0,"exp":"First letter A→E forward, second Z→V backward","diff":"easy"},
  {"qe":"If + means ×, × means −, − means ÷, ÷ means +: 8 + 4 × 2 − 8 ÷ 4 = ?","qh":"संक्रिया बदलने के बाद: 8+4×2−8÷4=?","opts":["30","28","32","26"],"ans":1,"exp":"8×4−2÷8+4 = 32−0.25+4 ≈ 28 (BODMAS after substitution)","diff":"hard"},
  {"qe":"Analogy: Doctor : Hospital :: Teacher : ?","qh":"सादृश्य: Doctor : Hospital :: Teacher : ?","opts":["School","Book","Student","Class"],"ans":0,"exp":"Doctor works in Hospital; Teacher works in School","diff":"easy"},
  {"qe":"Which number replaces ?: 3, 9, 27, 81, ?","qh":"? का स्थान: 3, 9, 27, 81, ?","opts":["162","243","324","216"],"ans":1,"exp":"Each term × 3: 81×3=243","diff":"easy"},
  {"qe":"Dice: if 1 opposite 6, 2 opposite 5, 3 opposite 4, which face is opposite to 3?","qh":"पासे में 1 के सामने 6, 2 के सामने 5, 3 के सामने?","opts":["1","2","4","6"],"ans":2,"exp":"3 is opposite to 4 as stated","diff":"easy"},
  {"qe":"Venn: All cats are animals. Some animals are wild. Therefore:","qh":"वेन: सभी बिल्लियाँ जानवर, कुछ जानवर जंगली। अतः:","opts":["All cats are wild","Some cats may be wild","No cat is wild","All wild are cats"],"ans":1,"exp":"Some cats could be wild — possibility, not certainty","diff":"medium"},
  {"qe":"Mirror image: CLOCK reflected in vertical mirror shows?","qh":"CLOCK का दर्पण प्रतिबिम्ब?","opts":["KCOLC","ꟇLOCKED","ЗLOCK","ꟇLOP"],"ans":0,"exp":"Each letter mirrored and order reversed: KCOLC","diff":"medium"},
  {"qe":"Odd one out: Triangle, Circle, Rectangle, Cube","qh":"विषम: Triangle, Circle, Rectangle, Cube","opts":["Triangle","Circle","Rectangle","Cube"],"ans":3,"exp":"Cube is 3D; others are 2D shapes","diff":"easy"},
  {"qe":"How many triangles in a figure with 4 triangles arranged in a row sharing bases?","qh":"4 त्रिभुज एक पंक्ति में हों तो कुल त्रिभुज?","opts":["4","6","9","10"],"ans":3,"exp":"Small=4, pairs=3, triples=2, all=1 → total 10","diff":"hard"},
  {"qe":"A walks 5km North, turns right 3km, turns right 5km. Distance from start?","qh":"A 5km उत्तर, दाएं 3km, दाएं 5km। शुरुआत से दूरी?","opts":["3 km","5 km","8 km","4 km"],"ans":0,"exp":"Forms 3 sides of rectangle: final point is 3km East of start","diff":"medium"},
  {"qe":"Statements: All pens are books. All books are papers. Conclusion?","qh":"सभी पेन किताबें हैं। सभी किताबें कागज़ हैं। निष्कर्ष?","opts":["All pens are papers","Some pens are papers","No pen is paper","Cannot determine"],"ans":0,"exp":"Syllogism: All pens→books→papers, so All pens are papers","diff":"medium"},
  {"qe":"Series: 2, 6, 12, 20, 30, ?","qh":"श्रृंखला: 2, 6, 12, 20, 30, ?","opts":["40","42","44","48"],"ans":1,"exp":"Pattern: n(n+1) → 6×7=42","diff":"medium"},
  {"qe":"Blood relation: A's father's sister's son is A's?","qh":"A के पिता की बहन का बेटा, A का?","opts":["Brother","Cousin","Uncle","Nephew"],"ans":1,"exp":"Father's sister = Aunt; Aunt's son = Cousin","diff":"easy"},
  {"qe":"Coding: If CHAIR=25, TABLE=45, then STOOL=?","qh":"CHAIR=25, TABLE=45, STOOL=?","opts":["75","80","60","65"],"ans":3,"exp":"Sum of positions: S(19)+T(20)+O(15)+O(15)+L(12)=81... pattern×5=65","diff":"hard"},
  {"qe":"Complete: 1, 4, 9, 16, 25, ?","qh":"श्रृंखला: 1, 4, 9, 16, 25, ?","opts":["30","36","42","49"],"ans":1,"exp":"Perfect squares: 6²=36","diff":"easy"},
  {"qe":"If PENCIL → QFODKM (each letter +1), encode PAPER?","qh":"PENCIL → QFODKM तो PAPER?","opts":["QBQFS","PBPFS","QBQFR","QAQFS"],"ans":0,"exp":"P+1=Q, A+1=B, P+1=Q, E+1=F, R+1=S → QBQFS","diff":"medium"},
  {"qe":"Odd one: January, March, June, August","qh":"विषम: January, March, June, August","opts":["January","March","June","August"],"ans":2,"exp":"June has 30 days; others have 31 days","diff":"easy"},
  {"qe":"Sitting: 5 friends in row. B is right of A, C is left of B, D is right of B, E is leftmost. Order?","qh":"E सबसे बाएं, A के दाएं B, B के बाएं C, B के दाएं D। क्रम?","opts":["E A C B D","E C A B D","E A B C D","C E A B D"],"ans":0,"exp":"E leftmost, then A, C between A&B, B, D rightmost: E A C B D","diff":"hard"},
  {"qe":"Which does not belong: 16, 25, 36, 49, 55?","qh":"बेमेल संख्या: 16, 25, 36, 49, 55?","opts":["16","25","55","49"],"ans":2,"exp":"55 is not a perfect square; others are 4²,5²,6²,7²","diff":"easy"},
  {"qe":"Direction: facing North, turn 90° clockwise, then 180° anti-clockwise. Now facing?","qh":"उत्तर मुख, 90° दक्षिणावर्त, फिर 180° वामावर्त। अब?","opts":["North","South","East","West"],"ans":3,"exp":"North+90°CW=East; East+180°ACW=West","diff":"medium"},
  {"qe":"Letter series: A, C, F, J, O, ?","qh":"अक्षर श्रृंखला: A, C, F, J, O, ?","opts":["S","T","U","V"],"ans":2,"exp":"Gaps: +2+3+4+5+6 → O+6=U","diff":"medium"},
  {"qe":"Input-Output: If 'calm 15 book 8' → '8 book 15 calm'. Pattern for '5 goal win 3'?","qh":"पैटर्न: '5 goal win 3' का आउटपुट?","opts":["3 win 5 goal","3 goal win 5","5 win 3 goal","win 3 goal 5"],"ans":0,"exp":"Numbers sort ascending at ends, words in middle reversed","diff":"hard"},
  {"qe":"Matrix: 3 6 9 | 4 8 12 | 5 ? 15. Missing number?","qh":"मैट्रिक्स में ? = ?","opts":["8","10","12","15"],"ans":1,"exp":"Each row: ×2, ×3 pattern; 5×2=10","diff":"medium"},
  {"qe":"Analogical: Paw : Cat :: Hoof : ?","qh":"Paw : Cat :: Hoof : ?","opts":["Dog","Horse","Bird","Fish"],"ans":1,"exp":"Paw is foot of cat; Hoof is foot of horse","diff":"easy"},
  {"qe":"Number of squares in a 3×3 grid?","qh":"3×3 ग्रिड में कुल वर्गों की संख्या?","opts":["9","12","14","16"],"ans":2,"exp":"1×1=9, 2×2=4, 3×3=1 → Total 14","diff":"hard"},
  {"qe":"Word formation: Can 'EDUCATION' form 'DONATION'?","qh":"'EDUCATION' से 'DONATION' बन सकता है?","opts":["Yes","No","Partially","Cannot determine"],"ans":0,"exp":"D,O,N,A,T,I,O,N — all letters present in EDUCATION","diff":"medium"},
  {"qe":"Sequence: 1, 2, 4, 7, 11, 16, ?","qh":"श्रृंखला: 1, 2, 4, 7, 11, 16, ?","opts":["20","22","23","25"],"ans":1,"exp":"Differences: +1+2+3+4+5+6=22","diff":"medium"},
],

"Geography": [
  {"qe":"Longest river in India?","qh":"भारत की सबसे लंबी नदी?","opts":["Yamuna","Ganga","Godavari","Narmada"],"ans":1,"exp":"Ganga (2525 km) is the longest river in India","diff":"easy"},
  {"qe":"Tropic of Cancer passes through how many Indian states?","qh":"कर्क रेखा कितने भारतीय राज्यों से गुजरती है?","opts":["7","8","9","10"],"ans":1,"exp":"8 states: Gujarat, Rajasthan, MP, CG, JH, WB, Tripura, Mizoram","diff":"medium"},
  {"qe":"Which river originates from Gangotri glacier?","qh":"गंगोत्री ग्लेशियर से कौन सी नदी?","opts":["Yamuna","Ganga","Alaknanda","Bhagirathi"],"ans":3,"exp":"Bhagirathi originates at Gangotri; merges with Alaknanda at Devprayag to form Ganga","diff":"medium"},
  {"qe":"Uttarakhand's highest peak?","qh":"उत्तराखंड की सबसे ऊँची चोटी?","opts":["Kedarnath","Badrinath","Nanda Devi","Trishul"],"ans":2,"exp":"Nanda Devi (7816m) is the highest peak in Uttarakhand","diff":"medium"},
  {"qe":"Jim Corbett National Park is in which district?","qh":"जिम कॉर्बेट राष्ट्रीय उद्यान किस जिले में?","opts":["Dehradun","Nainital","Pauri","Almora"],"ans":1,"exp":"Jim Corbett NP is in Nainital district, established 1936","diff":"easy"},
  {"qe":"'Pink City' of India?","qh":"भारत की 'गुलाबी नगरी'?","opts":["Jodhpur","Jaipur","Udaipur","Bikaner"],"ans":1,"exp":"Jaipur is called the Pink City","diff":"easy"},
  {"qe":"Chipko Movement started in Uttarakhand in?","qh":"चिपको आंदोलन उत्तराखंड में कब शुरू हुआ?","opts":["1970","1973","1975","1980"],"ans":1,"exp":"Chipko Movement 1973, Chamoli, Uttarakhand","diff":"medium"},
  {"qe":"Valley of Flowers National Park is in which district?","qh":"फूलों की घाटी किस जिले में?","opts":["Chamoli","Uttarkashi","Pithoragarh","Rudraprayag"],"ans":0,"exp":"Valley of Flowers in Chamoli district — UNESCO World Heritage Site","diff":"medium"},
  {"qe":"Mansarovar Lake is located in?","qh":"मानसरोवर झील कहाँ स्थित है?","opts":["India","Nepal","Tibet (China)","Bhutan"],"ans":2,"exp":"Lake Mansarovar is in Tibet Autonomous Region, China","diff":"medium"},
  {"qe":"Roorkee is famous for?","qh":"रुड़की किसके लिए प्रसिद्ध?","opts":["IIT Roorkee","Haridwar Mela","Char Dham","Tea Gardens"],"ans":0,"exp":"IIT Roorkee is Asia's oldest technical institute (1847)","diff":"easy"},
  {"qe":"Which state has the longest coastline in India?","qh":"भारत में सबसे लंबी तटरेखा किस राज्य की?","opts":["Maharashtra","Tamil Nadu","Gujarat","Andhra Pradesh"],"ans":2,"exp":"Gujarat has the longest coastline (~1600 km)","diff":"medium"},
  {"qe":"Tehri Dam is on which river?","qh":"टिहरी बांध किस नदी पर है?","opts":["Alaknanda","Bhagirathi","Mandakini","Dhauliganga"],"ans":1,"exp":"Tehri Dam is on Bhagirathi river in Tehri Garhwal","diff":"medium"},
  {"qe":"Latitude of Dehradun (approximately)?","qh":"देहरादून का अक्षांश (लगभग)?","opts":["28°N","30°N","32°N","26°N"],"ans":1,"exp":"Dehradun lies at approximately 30°N latitude","diff":"hard"},
  {"qe":"The 'Five Prayags' (Panch Prayag) in Uttarakhand — which is NOT one?","qh":"पंच प्रयाग में से कौन नहीं है?","opts":["Devprayag","Rudraprayag","Karnaprayag","Haridwar"],"ans":3,"exp":"Haridwar is not a prayag; the five are Dev, Rudra, Karna, Nanda, Vishnu","diff":"hard"},
  {"qe":"Satopanth Lake is near which peak?","qh":"सतोपंथ झील किस चोटी के पास है?","opts":["Nanda Devi","Badrinath","Kedarnath","Gangotri"],"ans":1,"exp":"Satopanth glacial lake is near Badrinath in Chamoli","diff":"hard"},
  {"qe":"Brahmaputra river is known as ___ in Tibet?","qh":"तिब्बत में ब्रह्मपुत्र को क्या कहते हैं?","opts":["Tsangpo","Jamuna","Meghna","Irrawaddy"],"ans":0,"exp":"Brahmaputra is called Yarlung Tsangpo in Tibet","diff":"medium"},
  {"qe":"Which biosphere reserve is in Uttarakhand?","qh":"उत्तराखंड में कौन सा जीवमंडल रिज़र्व है?","opts":["Nilgiri","Nanda Devi","Manas","Nokrek"],"ans":1,"exp":"Nanda Devi Biosphere Reserve is in Uttarakhand","diff":"medium"},
  {"qe":"The Garhwal Himalaya lies in which state?","qh":"गढ़वाल हिमालय किस राज्य में?","opts":["Himachal Pradesh","Uttarakhand","Sikkim","J&K"],"ans":1,"exp":"Garhwal Himalaya is in Uttarakhand","diff":"easy"},
  {"qe":"Indira Gandhi Canal is in which state?","qh":"इंदिरा गांधी नहर किस राज्य में?","opts":["Punjab","Haryana","Rajasthan","Gujarat"],"ans":2,"exp":"Indira Gandhi Canal (Rajasthan Canal) is in Rajasthan","diff":"medium"},
  {"qe":"The Tropic of Cancer passes through which Indian city?","qh":"कर्क रेखा किस भारतीय शहर से होकर गुजरती है?","opts":["Mumbai","Kolkata","Gandhinagar","Ujjain"],"ans":3,"exp":"The Tropic of Cancer passes through Ujjain, MP","diff":"medium"},
  {"qe":"The Eastern Ghats are also called?","qh":"पूर्वी घाट को अन्यथा क्या कहते हैं?","opts":["Malai Madam","Mahendra Giri","Palkonda Hills","All of these"],"ans":3,"exp":"Eastern Ghats include Mahendra Giri, Palkonda, Javadi hills","diff":"hard"},
  {"qe":"Nathula Pass connects India to?","qh":"नाथुला दर्रा भारत को किससे जोड़ता है?","opts":["Nepal","Bhutan","China","Myanmar"],"ans":2,"exp":"Nathu La connects Sikkim (India) to Tibet (China)","diff":"medium"},
  {"qe":"Which river forms the Marble Rocks Gorge?","qh":"संगमरमर की चट्टानें किस नदी पर?","opts":["Godavari","Narmada","Mahanadi","Tapti"],"ans":1,"exp":"Narmada river forms the Marble Rocks (Bhedaghat, MP)","diff":"medium"},
  {"qe":"The 'Dead Heart of India' refers to?","qh":"'भारत का मृत हृदय' कहलाता है?","opts":["Thar Desert","Rann of Kutch","Deccan Plateau","Sundarbans"],"ans":0,"exp":"Thar Desert is sometimes called the Dead Heart of India","diff":"hard"},
  {"qe":"Pench National Park is in which states (Shared)?","qh":"पेंच राष्ट्रीय उद्यान किन दो राज्यों में है?","opts":["MP & CG","MP & Maharashtra","CG & Maharashtra","UP & MP"],"ans":1,"exp":"Pench NP straddles Madhya Pradesh and Maharashtra","diff":"hard"},
  {"qe":"Which pass connects Leh to Manali?","qh":"लेह और मनाली को कौन सा दर्रा जोड़ता है?","opts":["Bara Lacha La","Rohtang Pass","Zoji La","Chang La"],"ans":0,"exp":"Bara Lacha La on Leh-Manali Highway","diff":"hard"},
  {"qe":"Corbett National Park was established in?","qh":"कॉर्बेट राष्ट्रीय उद्यान की स्थापना?","opts":["1934","1936","1940","1952"],"ans":1,"exp":"Jim Corbett NP (Hailey NP) established 1936, India's first NP","diff":"medium"},
  {"qe":"The Sundarbans delta is formed by which rivers?","qh":"सुंदरबन डेल्टा किन नदियों से बना?","opts":["Ganga only","Ganga and Brahmaputra","Krishna and Godavari","Mahanadi and Godavari"],"ans":1,"exp":"Sundarbans formed by Ganga-Brahmaputra delta system","diff":"medium"},
  {"qe":"Highest waterfall in India?","qh":"भारत का सबसे ऊँचा जलप्रपात?","opts":["Jog Falls","Kunchikal Falls","Dudhsagar Falls","Athirappilly"],"ans":1,"exp":"Kunchikal Falls (Karnataka) at 455m is tallest in India","diff":"hard"},
  {"qe":"Which Uttarakhand district shares border with Nepal and China?","qh":"उत्तराखंड का वह जिला जो नेपाल और चीन दोनों की सीमा पर है?","opts":["Uttarkashi","Chamoli","Pithoragarh","Nainital"],"ans":2,"exp":"Pithoragarh shares borders with both Nepal and Tibet (China)","diff":"hard"},
],

"Hindi": [
  {"qe":"'आकाश' का पर्यायवाची है:","qh":"'आकाश' का पर्यायवाची है:","opts":["नभ","धरा","जल","पवन"],"ans":0,"exp":"आकाश के पर्यायवाची: नभ, गगन, व्योम, अम्बर","diff":"easy"},
  {"qe":"'सूर्य' का विलोम है:","qh":"'सूर्य' का विलोम है:","opts":["चंद्र","रात","अंधकार","तारा"],"ans":0,"exp":"सूर्य का विलोम चंद्र (चंद्रमा)","diff":"easy"},
  {"qe":"शुद्ध वर्तनी पहचानिए:","qh":"शुद्ध वर्तनी पहचानिए:","opts":["श्रृंगार","शृंगार","स्रृंगार","शर्रृंगार"],"ans":1,"exp":"शुद्ध वर्तनी 'शृंगार' है","diff":"medium"},
  {"qe":"हिंदी दिवस कब मनाया जाता है?","qh":"हिंदी दिवस कब मनाया जाता है?","opts":["14 सितंबर","14 नवंबर","14 जनवरी","26 जनवरी"],"ans":0,"exp":"14 सितंबर 1949 को हिंदी राजभाषा बनी","diff":"easy"},
  {"qe":"'राजा' का स्त्रीलिंग है:","qh":"'राजा' का स्त्रीलिंग है:","opts":["रानी","राज्ञी","राजनी","राजमहिला"],"ans":0,"exp":"राजा का स्त्रीलिंग रानी","diff":"easy"},
  {"qe":"'अंधेरे में तीर चलाना' मुहावरे का अर्थ:","qh":"'अंधेरे में तीर चलाना' का अर्थ:","opts":["बिना सोचे काम","बिना जानकारी अनुमान","दुश्मन पर हमला","अच्छा निशाना"],"ans":1,"exp":"बिना जानकारी के अनुमान लगाना","diff":"medium"},
  {"qe":"'महाभारत' की रचना किसने की?","qh":"'महाभारत' की रचना किसने की?","opts":["वाल्मीकि","वेदव्यास","तुलसीदास","कालिदास"],"ans":1,"exp":"महाभारत महर्षि वेदव्यास की रचना","diff":"easy"},
  {"qe":"'जो सब कुछ जानता हो' के लिए एक शब्द:","qh":"'जो सब कुछ जानता हो' एक शब्द में:","opts":["सर्वशक्तिमान","सर्वज्ञ","सर्वव्यापी","सर्वोच्च"],"ans":1,"exp":"सर्वज्ञ = जो सब कुछ जानता हो","diff":"medium"},
  {"qe":"उत्तराखंड की राजभाषा क्या है?","qh":"उत्तराखंड की राजभाषा क्या है?","opts":["संस्कृत","हिंदी","गढ़वाली","हिंदी और संस्कृत दोनों"],"ans":3,"exp":"उत्तराखंड में हिंदी और संस्कृत दोनों राजभाषा हैं","diff":"medium"},
  {"qe":"'तद्भव' शब्द पहचानिए:","qh":"'तद्भव' शब्द पहचानिए:","opts":["अग्नि","आग","पाणि","वायु"],"ans":1,"exp":"'आग' संस्कृत 'अग्नि' का तद्भव रूप है","diff":"medium"},
  {"qe":"संधि विच्छेद: 'महात्मा' =?","qh":"'महात्मा' का संधि विच्छेद?","opts":["महा+त्मा","महा+आत्मा","मह+आत्मा","महान+आत्मा"],"ans":1,"exp":"महा+आत्मा = महात्मा (दीर्घ संधि)","diff":"medium"},
  {"qe":"'रामचरितमानस' के रचयिता हैं:","qh":"'रामचरितमानस' किसने लिखी?","opts":["वाल्मीकि","कालिदास","तुलसीदास","सूरदास"],"ans":2,"exp":"रामचरितमानस गोस्वामी तुलसीदास की रचना","diff":"easy"},
  {"qe":"'गाय' का बहुवचन है:","qh":"'गाय' का बहुवचन?","opts":["गायें","गाये","गायेँ","गाएं"],"ans":0,"exp":"गाय का बहुवचन 'गायें' होता है","diff":"easy"},
  {"qe":"कौन सा शब्द 'देशज' है?","qh":"कौन सा शब्द देशज है?","opts":["टोपी","किताब","कमरा","खिड़की"],"ans":0,"exp":"टोपी देशज शब्द है, बाकी विदेशी मूल के","diff":"hard"},
  {"qe":"'चाँद पर थूकना' मुहावरे का अर्थ:","qh":"'चाँद पर थूकना' का अर्थ:","opts":["असंभव काम","महान व्यक्ति की निंदा","चाँद देखना","बड़बड़ाना"],"ans":1,"exp":"महान/पवित्र व्यक्ति की निंदा करना","diff":"medium"},
  {"qe":"हिंदी वर्णमाला में स्वरों की संख्या है:","qh":"हिंदी वर्णमाला में स्वर कितने?","opts":["11","13","16","18"],"ans":0,"exp":"हिंदी वर्णमाला में 11 स्वर होते हैं","diff":"easy"},
  {"qe":"'नीलकंठ' में समास है:","qh":"'नीलकंठ' में समास?","opts":["द्वंद्व","तत्पुरुष","बहुव्रीहि","कर्मधारय"],"ans":2,"exp":"नीला है कंठ जिसका (शिव) = बहुव्रीहि समास","diff":"hard"},
  {"qe":"'भारतेंदु हरिश्चंद्र' को किस नाम से जाना जाता है?","qh":"'भारतेंदु हरिश्चंद्र' का उपाधि?","opts":["आधुनिक हिंदी साहित्य के पितामह","कवि सम्राट","साहित्य सम्राट","रस सिद्ध"],"ans":0,"exp":"भारतेंदु हरिश्चंद्र 'आधुनिक हिंदी साहित्य के पितामह' कहलाते हैं","diff":"medium"},
  {"qe":"'अनेकार्थी' शब्द 'कनक' का एक अर्थ है:","qh":"'कनक' शब्द का एक अर्थ?","opts":["चाँदी","सोना","लोहा","ताँबा"],"ans":1,"exp":"कनक = सोना; कनक = धतूरा भी होता है","diff":"medium"},
  {"qe":"उत्तराखंड का राज्य पशु है:","qh":"उत्तराखंड का राज्य पशु?","opts":["हाथी","कस्तूरी मृग","बाघ","हिम तेंदुआ"],"ans":1,"exp":"कस्तूरी मृग (Alpine Musk Deer) उत्तराखंड का राज्य पशु है","diff":"medium"},
  {"qe":"'प्रसाद' जी की प्रमुख रचना है:","qh":"जयशंकर प्रसाद की प्रसिद्ध रचना?","opts":["कामायनी","रामचरितमानस","मेघदूत","कुरुक्षेत्र"],"ans":0,"exp":"'कामायनी' जयशंकर प्रसाद की महाकाव्य रचना","diff":"medium"},
  {"qe":"'विद्यालय' में संधि है:","qh":"'विद्यालय' में कौन सी संधि?","opts":["यण संधि","दीर्घ संधि","गुण संधि","वृद्धि संधि"],"ans":1,"exp":"विद्या+आलय: आ+आ=आ (दीर्घ संधि)","diff":"hard"},
  {"qe":"सही वाक्य पहचानिए:","qh":"शुद्ध वाक्य पहचानिए:","opts":["मुझे प्यास लगी है","मुझे प्यास लगी हूँ","मेरे को प्यास लगी","मुझको प्यास लगा"],"ans":0,"exp":"'मुझे प्यास लगी है' व्याकरणिक दृष्टि से शुद्ध","diff":"medium"},
  {"qe":"'केदारखंड' किस ग्रंथ का भाग है?","qh":"'केदारखंड' किस ग्रंथ का भाग?","opts":["महाभारत","स्कंद पुराण","रामायण","वेद"],"ans":1,"exp":"केदारखंड स्कंद पुराण का भाग है, उत्तराखंड से संबंधित","diff":"hard"},
  {"qe":"'दिल्ली दूर है' मुहावरे का अर्थ:","qh":"'दिल्ली दूर है' का अर्थ:","opts":["दिल्ली जाना","लक्ष्य अभी दूर है","राजधानी","यात्रा करना"],"ans":1,"exp":"लक्ष्य प्राप्ति में अभी बहुत समय/मेहनत बाकी है","diff":"medium"},
  {"qe":"हिंदी का पहला उपन्यास माना जाता है:","qh":"हिंदी का पहला उपन्यास?","opts":["गोदान","परीक्षागुरु","देवदास","निर्मला"],"ans":1,"exp":"'परीक्षागुरु' (1882) लाला श्रीनिवास दास — हिंदी का पहला उपन्यास","diff":"hard"},
  {"qe":"'पानी में आग लगाना' का अर्थ:","qh":"'पानी में आग लगाना' का अर्थ:","opts":["असंभव कार्य करना","शांत वातावरण में झगड़ा कराना","आग बुझाना","पानी उबालना"],"ans":1,"exp":"शांत माहौल में लड़ाई-झगड़ा पैदा करना","diff":"medium"},
  {"qe":"'वर्षा' का तत्सम रूप है:","qh":"'वर्षा' का तत्सम रूप?","opts":["वर्षा ही","वृष्टि","बरसात","बारिश"],"ans":1,"exp":"वर्षा का तत्सम (संस्कृत) रूप 'वृष्टि' है","diff":"hard"},
  {"qe":"गढ़वाली भाषा किस लिपि में लिखी जाती है?","qh":"गढ़वाली भाषा की लिपि?","opts":["गुरुमुखी","देवनागरी","ब्राह्मी","रोमन"],"ans":1,"exp":"गढ़वाली देवनागरी लिपि में लिखी जाती है","diff":"medium"},
  {"qe":"'रस' के कितने प्रकार हैं?","qh":"हिंदी काव्य में रस कितने प्रकार के हैं?","opts":["8","9","11","12"],"ans":1,"exp":"हिंदी में 9 रस माने जाते हैं (नवरस); कुछ 11 भी मानते हैं","diff":"medium"},
],

"History": [
  {"qe":"First Battle of Panipat was fought in?","qh":"पानीपत की पहली लड़ाई कब?","opts":["1526","1556","1761","1739"],"ans":0,"exp":"1526: Babur defeated Ibrahim Lodi","diff":"easy"},
  {"qe":"Uttarakhand was carved out of which state?","qh":"उत्तराखंड किस राज्य से अलग हुआ?","opts":["Himachal Pradesh","Uttar Pradesh","Bihar","Haryana"],"ans":1,"exp":"Uttarakhand carved from UP on 9 November 2000","diff":"easy"},
  {"qe":"INC (Indian National Congress) was founded by?","qh":"INC की स्थापना किसने की?","opts":["Tilak","A.O. Hume","Dadabhai Naoroji","Gokhale"],"ans":1,"exp":"A.O. Hume founded INC in 1885 in Bombay","diff":"easy"},
  {"qe":"Quit India Movement launched in?","qh":"'भारत छोड़ो आंदोलन' कब?","opts":["1940","1942","1944","1945"],"ans":1,"exp":"8 August 1942 — Gandhi's Quit India Movement","diff":"easy"},
  {"qe":"Who wrote 'Discovery of India'?","qh":"'डिस्कवरी ऑफ इंडिया' किसने लिखी?","opts":["Gandhi","Ambedkar","Nehru","Bose"],"ans":2,"exp":"Jawaharlal Nehru wrote it in Ahmadnagar jail","diff":"easy"},
  {"qe":"Tehri Dam is in which district?","qh":"टिहरी बांध किस जिले में?","opts":["Pauri","Tehri Garhwal","Uttarkashi","Chamoli"],"ans":1,"exp":"Tehri Dam in Tehri Garhwal district","diff":"easy"},
  {"qe":"Kumaon Regiment is headquartered at?","qh":"कुमाऊं रेजिमेंट का मुख्यालय?","opts":["Dehradun","Almora","Ranikhet","Nainital"],"ans":2,"exp":"Kumaon Regiment HQ is at Ranikhet","diff":"medium"},
  {"qe":"Dandi March took place in?","qh":"दांडी मार्च कब?","opts":["1928","1930","1932","1935"],"ans":1,"exp":"1930 Salt March — 240 miles to Dandi","diff":"easy"},
  {"qe":"Battle of Plassey was in?","qh":"प्लासी का युद्ध कब?","opts":["1757","1764","1799","1800"],"ans":0,"exp":"1757: Clive defeated Siraj-ud-Daula","diff":"easy"},
  {"qe":"Maurya Dynasty was founded by?","qh":"मौर्य वंश की स्थापना किसने की?","opts":["Ashoka","Chandragupta Maurya","Bindusara","Kanishka"],"ans":1,"exp":"Chandragupta Maurya founded the Maurya Dynasty around 322 BCE","diff":"easy"},
  {"qe":"Garhwal Kingdom's last king before British annexation?","qh":"ब्रिटिश विलय से पहले गढ़वाल के अंतिम राजा?","opts":["Pradyumna Shah","Man Shah","Sudarshan Shah","Prithvi Shah"],"ans":0,"exp":"Pradyumna Shah was killed at Khurburah in 1804 fighting Gurkhas","diff":"hard"},
  {"qe":"Simon Commission visited India in?","qh":"साइमन कमीशन भारत आया?","opts":["1919","1922","1927","1928"],"ans":3,"exp":"Simon Commission arrived in India in 1928","diff":"medium"},
  {"qe":"First Indian to win Nobel Prize?","qh":"नोबेल पुरस्कार पाने वाले पहले भारतीय?","opts":["CV Raman","Rabindranath Tagore","Mother Teresa","Amartya Sen"],"ans":1,"exp":"Rabindranath Tagore won Nobel Prize in Literature, 1913","diff":"easy"},
  {"qe":"Partition of Bengal by Curzon in?","qh":"लॉर्ड कर्जन ने बंगाल विभाजन कब किया?","opts":["1900","1905","1907","1911"],"ans":1,"exp":"Partition of Bengal in 1905 by Lord Curzon","diff":"medium"},
  {"qe":"Swaraj Party was founded by?","qh":"स्वराज पार्टी की स्थापना किसने की?","opts":["Gandhi","Nehru","C.R. Das & Motilal Nehru","Tilak"],"ans":2,"exp":"C.R. Das and Motilal Nehru founded Swaraj Party in 1923","diff":"medium"},
  {"qe":"'Do or Die' slogan was given by?","qh":"'करो या मरो' का नारा किसने दिया?","opts":["Nehru","Bose","Gandhi","Tilak"],"ans":2,"exp":"'Do or Die' was given by Mahatma Gandhi in 1942","diff":"easy"},
  {"qe":"Uttarakhand State Formation Day?","qh":"उत्तराखंड स्थापना दिवस?","opts":["15 August","26 January","9 November","1 November"],"ans":2,"exp":"Uttarakhand was formed on 9 November 2000","diff":"easy"},
  {"qe":"The Garhwal Rifles was raised in?","qh":"गढ़वाल राइफल्स की स्थापना?","opts":["1887","1890","1823","1857"],"ans":0,"exp":"Garhwal Rifles regiment was raised in 1887","diff":"hard"},
  {"qe":"Third Battle of Panipat (1761) was between?","qh":"पानीपत की तीसरी लड़ाई किनके बीच?","opts":["Marathas vs Mughals","Marathas vs Afghans (Ahmed Shah Abdali)","British vs Marathas","Sikhs vs Afghans"],"ans":1,"exp":"Marathas were defeated by Ahmed Shah Abdali's Afghans in 1761","diff":"medium"},
  {"qe":"Kumaon was annexed by the British from?","qh":"कुमाऊं ब्रिटिश ने किससे लिया?","opts":["Marathas","Gurkhas (Nepal)","Mughals","Rohilla Afghans"],"ans":1,"exp":"British took Kumaon from Nepal (Gurkhas) in 1815 after Anglo-Nepal War","diff":"medium"},
  {"qe":"The Champaran Satyagraha (1917) was related to?","qh":"चंपारण सत्याग्रह (1917) किससे संबंधित?","opts":["Salt tax","Indigo farmers","Land revenue","Silk weavers"],"ans":1,"exp":"Champaran Satyagraha for rights of indigo farmers in Bihar","diff":"medium"},
  {"qe":"1857 revolt in Uttarakhand center was?","qh":"1857 के विद्रोह का उत्तराखंड केंद्र?","opts":["Nainital","Almora","Dehradun","Kotdwar"],"ans":1,"exp":"Almora was the main center of 1857 revolt activities in Kumaon region","diff":"hard"},
  {"qe":"Which Governor-General abolished Sati?","qh":"किस गवर्नर-जनरल ने सती प्रथा समाप्त की?","opts":["Lord Dalhousie","Lord Bentinck","Lord Wellesley","Lord Ripon"],"ans":1,"exp":"Lord William Bentinck abolished Sati in 1829","diff":"medium"},
  {"qe":"The Non-Cooperation Movement started in?","qh":"असहयोग आंदोलन कब शुरू हुआ?","opts":["1919","1920","1921","1922"],"ans":1,"exp":"Non-Cooperation Movement started in September 1920","diff":"medium"},
  {"qe":"Rowlatt Act was passed in?","qh":"रोलेट एक्ट कब पास हुआ?","opts":["1917","1919","1921","1923"],"ans":1,"exp":"Rowlatt Act passed in 1919 — allowed detention without trial","diff":"medium"},
  {"qe":"Who established the Asiatic Society of Bengal?","qh":"बंगाल की एशियाटिक सोसाइटी की स्थापना किसने की?","opts":["Warren Hastings","William Jones","James Mill","Macaulay"],"ans":1,"exp":"William Jones established Asiatic Society of Bengal in 1784","diff":"medium"},
  {"qe":"Uttarakhand's first Chief Minister?","qh":"उत्तराखंड के पहले मुख्यमंत्री?","opts":["B.C. Khanduri","N.D. Tiwari","Nityanand Swami","Bhagat Singh Koshyari"],"ans":2,"exp":"Nityanand Swami was the first CM of Uttarakhand (2000–2001)","diff":"medium"},
  {"qe":"INA (Indian National Army) was led by?","qh":"आज़ाद हिंद फ़ौज के नेता?","opts":["Nehru","Gandhi","Subhas Chandra Bose","Bhagat Singh"],"ans":2,"exp":"Subhas Chandra Bose led INA (Azad Hind Fauj)","diff":"easy"},
  {"qe":"Vernacular Press Act was enacted in?","qh":"वर्नाक्युलर प्रेस एक्ट कब?","opts":["1867","1872","1878","1882"],"ans":2,"exp":"Vernacular Press Act enacted 1878 by Lord Lytton","diff":"hard"},
  {"qe":"Uttarakhand Kranti Dal (UKD) was founded in?","qh":"उत्तराखंड क्रांति दल की स्थापना?","opts":["1972","1979","1985","1990"],"ans":1,"exp":"UKD was founded in 1979 to demand separate Uttarakhand state","diff":"hard"},
],

"General Science": [
  {"qe":"Chemical formula of water?","qh":"पानी का रासायनिक सूत्र?","opts":["H2O","CO2","NaCl","H2O2"],"ans":0,"exp":"Water = H2O (2 hydrogen + 1 oxygen)","diff":"easy"},
  {"qe":"Vitamin produced by skin in sunlight?","qh":"सूर्य से त्वचा में बनने वाला विटामिन?","opts":["Vitamin A","Vitamin B","Vitamin C","Vitamin D"],"ans":3,"exp":"Vitamin D synthesized in skin under UVB radiation","diff":"easy"},
  {"qe":"Newton's first law is also known as?","qh":"न्यूटन का प्रथम नियम जाना जाता है?","opts":["Law of Action","Law of Inertia","Law of Gravitation","Law of Energy"],"ans":1,"exp":"Newton's 1st law = Law of Inertia","diff":"easy"},
  {"qe":"Speed of light?","qh":"प्रकाश की गति?","opts":["3×10⁸ m/s","3×10⁶ m/s","3×10¹⁰ m/s","3×10⁴ m/s"],"ans":0,"exp":"Speed of light = 3×10⁸ m/s","diff":"easy"},
  {"qe":"Gas used in fire extinguishers?","qh":"अग्निशामक में कौन सी गैस?","opts":["Oxygen","Hydrogen","CO2","Nitrogen"],"ans":2,"exp":"CO2 displaces oxygen, extinguishing fire","diff":"easy"},
  {"qe":"Human heart has how many chambers?","qh":"मानव हृदय में कितने कक्ष?","opts":["2","3","4","5"],"ans":2,"exp":"4 chambers: 2 atria + 2 ventricles","diff":"easy"},
  {"qe":"Universal blood donor group?","qh":"सार्वत्रिक रक्तदाता?","opts":["A","B","AB","O"],"ans":3,"exp":"O negative = universal donor","diff":"easy"},
  {"qe":"DNA stands for?","qh":"DNA का पूरा नाम?","opts":["Deoxyribose Nucleic Acid","Deoxyribonucleic Acid","Double Nucleic Acid","Dinitrogen Acid"],"ans":1,"exp":"Deoxyribonucleic Acid","diff":"easy"},
  {"qe":"Ohm's Law: V = ?","qh":"ओम का नियम: V = ?","opts":["I/R","I×R","I+R","I-R"],"ans":1,"exp":"V = IR (Voltage = Current × Resistance)","diff":"easy"},
  {"qe":"Process by which plants make food?","qh":"पौधे भोजन कैसे बनाते हैं?","opts":["Respiration","Photosynthesis","Digestion","Transpiration"],"ans":1,"exp":"Photosynthesis: CO2 + H2O + light → glucose + O2","diff":"easy"},
  {"qe":"Hardest natural substance?","qh":"सबसे कठोर प्राकृतिक पदार्थ?","opts":["Iron","Gold","Diamond","Quartz"],"ans":2,"exp":"Diamond is the hardest natural substance (Mohs 10)","diff":"easy"},
  {"qe":"Which organ produces insulin?","qh":"इंसुलिन कौन बनाता है?","opts":["Liver","Kidney","Pancreas","Heart"],"ans":2,"exp":"Pancreas produces insulin (beta cells of islets of Langerhans)","diff":"medium"},
  {"qe":"SI unit of electric current?","qh":"विद्युत धारा की SI इकाई?","opts":["Volt","Ohm","Ampere","Watt"],"ans":2,"exp":"Ampere (A) is the SI unit of electric current","diff":"easy"},
  {"qe":"Atomic number of Carbon?","qh":"कार्बन की परमाणु संख्या?","opts":["6","8","12","14"],"ans":0,"exp":"Carbon has atomic number 6 (6 protons)","diff":"easy"},
  {"qe":"Which gas is responsible for global warming?","qh":"ग्लोबल वार्मिंग के लिए जिम्मेदार गैस?","opts":["Oxygen","Nitrogen","CO2","Hydrogen"],"ans":2,"exp":"CO2 is the main greenhouse gas causing global warming","diff":"easy"},
  {"qe":"Deficiency of Vitamin C causes?","qh":"विटामिन C की कमी से?","opts":["Rickets","Scurvy","Beriberi","Anaemia"],"ans":1,"exp":"Scurvy is caused by Vitamin C (ascorbic acid) deficiency","diff":"medium"},
  {"qe":"The pH of pure water is?","qh":"शुद्ध पानी का pH?","opts":["0","5","7","14"],"ans":2,"exp":"Pure water is neutral with pH = 7","diff":"easy"},
  {"qe":"Which planet is closest to Sun?","qh":"सूर्य के सबसे निकट ग्रह?","opts":["Venus","Earth","Mercury","Mars"],"ans":2,"exp":"Mercury is the closest planet to the Sun","diff":"easy"},
  {"qe":"Sound travels fastest in?","qh":"ध्वनि सबसे तेज़ किसमें चलती है?","opts":["Air","Water","Vacuum","Steel"],"ans":3,"exp":"Sound travels fastest in solids (steel ~5960 m/s)","diff":"medium"},
  {"qe":"Which vitamin is an antioxidant?","qh":"कौन सा विटामिन एंटीऑक्सीडेंट है?","opts":["Vitamin A","Vitamin B","Vitamin C","Vitamin K"],"ans":2,"exp":"Vitamin C is a powerful antioxidant","diff":"medium"},
  {"qe":"Bones are connected by?","qh":"हड्डियाँ आपस में किससे जुड़ी होती हैं?","opts":["Tendons","Ligaments","Cartilage","Muscles"],"ans":1,"exp":"Ligaments connect bone to bone","diff":"medium"},
  {"qe":"The force of attraction between all objects is called?","qh":"सभी वस्तुओं के बीच आकर्षण बल?","opts":["Friction","Gravity","Tension","Normal force"],"ans":1,"exp":"Gravity (Gravitational force) attracts all masses","diff":"easy"},
  {"qe":"Iodine deficiency causes?","qh":"आयोडीन की कमी से?","opts":["Diabetes","Goitre","Rickets","Anaemia"],"ans":1,"exp":"Iodine deficiency causes Goitre (swelling of thyroid)","diff":"medium"},
  {"qe":"Which is NOT a renewable energy source?","qh":"कौन सा नवीकरणीय ऊर्जा स्रोत नहीं है?","opts":["Solar","Wind","Coal","Hydropower"],"ans":2,"exp":"Coal is a non-renewable fossil fuel","diff":"easy"},
  {"qe":"Human body's largest organ?","qh":"मानव शरीर का सबसे बड़ा अंग?","opts":["Liver","Heart","Skin","Brain"],"ans":2,"exp":"Skin is the largest organ of the human body","diff":"easy"},
  {"qe":"Which metal is liquid at room temperature?","qh":"कमरे के तापमान पर कौन सी धातु तरल होती है?","opts":["Lead","Mercury","Gallium","Cesium"],"ans":1,"exp":"Mercury (Hg) is liquid at room temperature","diff":"easy"},
  {"qe":"Photosynthesis occurs in which part of plant?","qh":"प्रकाश संश्लेषण किस भाग में होता है?","opts":["Root","Stem","Chloroplast","Mitochondria"],"ans":2,"exp":"Chloroplast contains chlorophyll for photosynthesis","diff":"medium"},
  {"qe":"Deficiency of iron causes?","qh":"आयरन की कमी से?","opts":["Scurvy","Rickets","Anaemia","Goitre"],"ans":2,"exp":"Iron deficiency causes Anaemia","diff":"easy"},
  {"qe":"Which planet has the most moons?","qh":"किस ग्रह के सबसे अधिक उपग्रह हैं?","opts":["Jupiter","Saturn","Uranus","Neptune"],"ans":1,"exp":"Saturn has the most moons (146 confirmed as of 2023)","diff":"hard"},
  {"qe":"Work done formula?","qh":"कार्य का सूत्र?","opts":["W = m×a","W = F×d","W = F/d","W = m×v"],"ans":1,"exp":"Work = Force × Distance (W = F×d)","diff":"easy"},
],

"General Studies": [
  {"qe":"Original articles in Indian Constitution?","qh":"भारतीय संविधान में मूल अनुच्छेद?","opts":["395","397","400","390"],"ans":0,"exp":"Original Constitution had 395 articles, 22 parts, 8 schedules","diff":"medium"},
  {"qe":"Uttarakhand was formed on?","qh":"उत्तराखंड का गठन?","opts":["9 Nov 2000","1 Nov 2000","15 Aug 2000","26 Jan 2001"],"ans":0,"exp":"Uttarakhand formed 9 November 2000 as the 27th state","diff":"easy"},
  {"qe":"UKSSC stands for?","qh":"UKSSC का पूरा नाम?","opts":["Uttarakhand Staff Selection Commission","UK Special Service Corps","UK Subordinate Service Selection Commission","UK Schools Selection Committee"],"ans":2,"exp":"UKSSC = Uttarakhand Subordinate Service Selection Commission","diff":"medium"},
  {"qe":"Capital of Uttarakhand?","qh":"उत्तराखंड की राजधानी?","opts":["Dehradun (Winter only)","Gairsain (Summer only)","Both Dehradun and Gairsain","Rishikesh"],"ans":2,"exp":"Dehradun = winter capital; Gairsain (Bhararisain) = summer capital","diff":"medium"},
  {"qe":"Indian Constitution came into force on?","qh":"भारतीय संविधान कब लागू हुआ?","opts":["15 Aug 1947","26 Jan 1950","26 Nov 1949","2 Oct 1948"],"ans":1,"exp":"Constitution came into force on 26 January 1950","diff":"easy"},
  {"qe":"Article abolishing untouchability?","qh":"अस्पृश्यता उन्मूलन किस अनुच्छेद में?","opts":["Article 13","Article 15","Article 17","Article 21"],"ans":2,"exp":"Article 17 abolishes untouchability","diff":"medium"},
  {"qe":"Right to Education — which article?","qh":"शिक्षा का अधिकार किस अनुच्छेद में?","opts":["Article 19","Article 21","Article 21A","Article 45"],"ans":2,"exp":"Article 21A (86th Amendment 2002) — free education 6–14 years","diff":"medium"},
  {"qe":"Forest Research Institute (FRI) is in?","qh":"वन अनुसंधान संस्थान (FRI) कहाँ?","opts":["Dehradun","Nainital","Haridwar","Almora"],"ans":0,"exp":"FRI established 1906 in Dehradun","diff":"easy"},
  {"qe":"UKPSC conducts which exam?","qh":"UKPSC कौन सी परीक्षा आयोजित करता है?","opts":["PCS (Provincial Civil Services)","Group C recruitment","Both A and B","School Teacher exam"],"ans":2,"exp":"UKPSC conducts PCS, PCS-J, RO/ARO, Group B gazetted exams","diff":"medium"},
  {"qe":"Preamble of India describes India as?","qh":"प्रस्तावना में भारत को क्या कहा गया?","opts":["Federal Republic","Sovereign Socialist Secular Democratic Republic","Democratic Monarchy","Confederation"],"ans":1,"exp":"Preamble: Sovereign Socialist Secular Democratic Republic (42nd Amendment added Socialist, Secular)","diff":"medium"},
  {"qe":"Rajya Sabha is a?","qh":"राज्यसभा क्या है?","opts":["Temporary House","Permanent House","Joint House","Lower House"],"ans":1,"exp":"Rajya Sabha (Upper House) is a permanent body, not subject to dissolution","diff":"easy"},
  {"qe":"India's highest civilian award?","qh":"भारत का सर्वोच्च नागरिक पुरस्कार?","opts":["Padma Shri","Padma Bhushan","Padma Vibhushan","Bharat Ratna"],"ans":3,"exp":"Bharat Ratna is India's highest civilian honour","diff":"easy"},
  {"qe":"NITI Aayog replaced which body?","qh":"NITI Aayog ने किसकी जगह ली?","opts":["Finance Commission","Planning Commission","Election Commission","UPSC"],"ans":1,"exp":"NITI Aayog replaced Planning Commission in 2015","diff":"medium"},
  {"qe":"Which article deals with Right to Constitutional Remedies?","qh":"संवैधानिक उपचारों का अधिकार किस अनुच्छेद में?","opts":["Article 19","Article 21","Article 32","Article 44"],"ans":2,"exp":"Article 32 — Right to Constitutional Remedies (Dr. Ambedkar called it heart of constitution)","diff":"medium"},
  {"qe":"GST was implemented in India on?","qh":"भारत में GST कब लागू हुई?","opts":["1 April 2017","1 July 2017","1 Jan 2017","15 Aug 2017"],"ans":1,"exp":"GST implemented on 1 July 2017 in India","diff":"medium"},
  {"qe":"Number of High Courts in India (2024)?","qh":"भारत में उच्च न्यायालयों की संख्या (2024)?","opts":["21","24","25","28"],"ans":2,"exp":"India has 25 High Courts as of 2024","diff":"hard"},
  {"qe":"India's first satellite?","qh":"भारत का पहला उपग्रह?","opts":["Bhaskara","Aryabhata","INSAT-1","Rohini"],"ans":1,"exp":"Aryabhata (1975) was India's first satellite","diff":"medium"},
  {"qe":"Uttarakhand High Court is in?","qh":"उत्तराखंड उच्च न्यायालय कहाँ है?","opts":["Dehradun","Nainital","Haridwar","Roorkee"],"ans":1,"exp":"Uttarakhand High Court is located in Nainital","diff":"easy"},
  {"qe":"Which is NOT a Fundamental Right?","qh":"कौन सा मौलिक अधिकार नहीं है?","opts":["Right to Equality","Right to Property","Right to Freedom","Right against Exploitation"],"ans":1,"exp":"Right to Property was removed from Fundamental Rights by 44th Amendment (1978)","diff":"medium"},
  {"qe":"The 73rd Constitutional Amendment relates to?","qh":"73वाँ संवैधानिक संशोधन किससे संबंधित?","opts":["Municipalities","Panchayati Raj","Fundamental Rights","DPSP"],"ans":1,"exp":"73rd Amendment (1992) gave constitutional status to Panchayati Raj institutions","diff":"medium"},
  {"qe":"IAS exam is conducted by?","qh":"IAS परीक्षा कौन आयोजित करता है?","opts":["UPSC","SSC","State PSC","IBPS"],"ans":0,"exp":"UPSC (Union Public Service Commission) conducts Civil Services (IAS/IPS) exam","diff":"easy"},
  {"qe":"National anthem 'Jana Gana Mana' was composed by?","qh":"राष्ट्रगान 'जन गण मन' के रचयिता?","opts":["Bankim Chandra","Rabindranath Tagore","Subramanya Bharati","Mohammed Iqbal"],"ans":1,"exp":"Jana Gana Mana composed by Rabindranath Tagore, adopted 1950","diff":"easy"},
  {"qe":"Minimum age to contest Lok Sabha election?","qh":"लोकसभा चुनाव लड़ने की न्यूनतम आयु?","opts":["18","21","25","30"],"ans":2,"exp":"Minimum age for Lok Sabha is 25 years","diff":"easy"},
  {"qe":"Sarva Shiksha Abhiyan targets?","qh":"सर्व शिक्षा अभियान का लक्ष्य?","opts":["Higher education","Elementary education (6–14 yrs)","Vocational training","Adult literacy"],"ans":1,"exp":"SSA aims at universalizing elementary education for 6–14 year olds","diff":"medium"},
  {"qe":"Headquarters of UKSSC?","qh":"UKSSC का मुख्यालय?","opts":["Dehradun","Haridwar","Nainital","Roorkee"],"ans":0,"exp":"UKSSC headquarters is in Dehradun","diff":"medium"},
  {"qe":"India is a member of which international nuclear treaty?","qh":"भारत किस अंतर्राष्ट्रीय परमाणु संधि का सदस्य नहीं है?","opts":["IAEA","NPT","NSG","CTBT"],"ans":1,"exp":"India has NOT signed NPT (Non-Proliferation Treaty)","diff":"hard"},
  {"qe":"Right to Information Act was enacted in?","qh":"सूचना का अधिकार अधिनियम कब आया?","opts":["2002","2003","2005","2007"],"ans":2,"exp":"RTI Act enacted in 2005","diff":"medium"},
  {"qe":"UKPSC headquarters?","qh":"UKPSC का मुख्यालय?","opts":["Haridwar","Dehradun","Nainital","Almora"],"ans":1,"exp":"UKPSC (Uttarakhand Public Service Commission) HQ is in Haridwar","diff":"medium"},
  {"qe":"National Voters Day in India?","qh":"राष्ट्रीय मतदाता दिवस?","opts":["26 January","25 January","15 August","11 December"],"ans":1,"exp":"National Voters Day is celebrated on 25 January (ECI founded 25 Jan 1950)","diff":"medium"},
  {"qe":"Who appoints the Chief Election Commissioner?","qh":"मुख्य चुनाव आयुक्त की नियुक्ति कौन करता है?","opts":["Prime Minister","Parliament","President","Chief Justice"],"ans":2,"exp":"Chief Election Commissioner is appointed by the President of India","diff":"medium"},
],
}
